<footer class="site-footer">
  <div class="footer-grid">
    <div class="footer-brand">
      <h3>WorldNews.org.au</h3>
      <p>An autonomous AI-powered news aggregation platform monitoring global RSS feeds across 47 countries. Stories are aggregated, synthesised, and rewritten by AI every 15 minutes.</p>
      <div class="ai-disclosure">
        AI DISCLOSURE: All content on this site is generated by artificial intelligence from publicly available news sources. WorldNews.org.au does not employ journalists. Sources are cited within each article. For corrections: <a href="mailto:editorial@worldnews.org.au" style="color:var(--gold);">editorial@worldnews.org.au</a>
      </div>
    </div>
    <div class="footer-col">
      <h4>Sections</h4>
      <?php
      $cats = get_categories(array('number'=>8,'orderby'=>'count','order'=>'DESC'));
      foreach ($cats as $cat) {
        echo '<a href="' . get_category_link($cat->term_id) . '">' . esc_html($cat->name) . '</a>';
      }
      ?>
    </div>
    <div class="footer-col">
      <h4>Platform</h4>
      <a href="<?php echo home_url('/about'); ?>">About WorldNews</a>
      <a href="<?php echo home_url('/ai-methodology'); ?>">AI Methodology</a>
      <a href="<?php echo home_url('/advertise'); ?>">Advertise With Us</a>
      <a href="<?php echo home_url('/affiliate-disclosure'); ?>">Affiliate Disclosure</a>
    </div>
    <div class="footer-col">
      <h4>Legal</h4>
      <a href="<?php echo home_url('/privacy-policy'); ?>">Privacy Policy</a>
      <a href="<?php echo home_url('/terms-of-service'); ?>">Terms of Service</a>
      <a href="<?php echo home_url('/ai-content-policy'); ?>">AI Content Policy</a>
      <a href="<?php echo home_url('/contact'); ?>">Contact</a>
    </div>
  </div>
  <div class="footer-bottom">
    <span>© <?php echo date('Y'); ?> WorldNews.org.au · All Rights Reserved</span>
    <span>AI-POWERED · AUTONOMOUS PUBLISHING · CONTINUOUSLY UPDATED</span>
    <span>worldnews.org.au</span>
  </div>
</footer>
<?php wp_footer(); ?>
</body>
</html>
